"""Pydantic models for the FastAPI ingestion wire format.

Why a wire model layer at all?
------------------------------
:class:`eurpe.schema.ProposalMetadata` is the *internal* model used by the
chunker, the index, and the YAML sidecar. Exposing it directly on the HTTP
boundary has two problems:

1. Internal fields drift. ``source_path`` is supplied by the server (it
   points at the staged PDF on disk); ``ingested_at`` is generated by the
   server. Letting clients write either field would either leak server
   paths into the request or let a misconfigured client overwrite the
   audit timestamp.
2. ``ProposalMetadata`` carries ``extra="forbid"`` for safety, which
   means *adding* a wire-only field (``parse_token``) would have to live
   somewhere else anyway.

The wire models below mirror only the fields the operator actually edits
in the React confirmation form; the route reconstructs the full
:class:`ProposalMetadata` server-side after lookup of the parse token.
``extra="forbid"`` is preserved on every wire model so an unexpected
field in the JSON body fails fast with a 422 instead of being silently
ignored.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from eurpe.schema import Programme, SectionType, SourceStatus


class ParseResponse(BaseModel):
    """What ``POST /api/ingestion/parse`` returns to the UI.

    The ``parse_token`` is a UUID4 string the client must echo back to
    ``POST /api/ingestion/confirm`` so the route can find the staged PDF
    and the server-extracted draft metadata. Tokens have a TTL (see
    :class:`eurpe.api.storage.ParseTokenStore`); expired tokens return
    ``404 Not Found`` from the confirm route.

    ``suggested`` is the best-effort metadata draft the server inferred
    from the filename plus any in-document hints. The UI pre-populates
    the confirmation form with these values; the operator is expected
    to review and override anything wrong.
    """

    model_config = ConfigDict(extra="forbid")

    parse_token: str = Field(min_length=1, description="Token to use with /confirm.")
    source_path: str = Field(min_length=1, description="Where the PDF was staged on disk.")
    parsed_at: datetime = Field(description="When the parser finished, UTC.")
    suggested: dict = Field(
        default_factory=dict,
        description=(
            "Best-effort metadata draft inferred from the filename, surfaced as a "
            "plain dict so the UI can render the values verbatim and let the "
            "operator override anything inferred wrongly."
        ),
    )
    page_count: int | None = Field(
        default=None,
        description="Page count reported by Docling, if available.",
    )
    title: str | None = Field(
        default=None,
        description="Document title recovered by Docling, if any.",
    )
    section_count: int = Field(
        default=0,
        description="How many top-level sections Docling extracted.",
    )


class ConfirmRequest(BaseModel):
    """Operator-confirmed metadata submitted to ``POST /api/ingestion/confirm``.

    Only the fields the operator can edit appear here. ``source_path`` and
    ``ingested_at`` are server-generated; ``language`` defaults to ``en`` to
    match :class:`ProposalMetadata` and may be overridden if needed.
    """

    model_config = ConfigDict(extra="forbid")

    parse_token: str = Field(min_length=1, description="Token from /parse.")
    programme: Programme = Field(description="Confirmed EU funding programme.")
    call_id: str = Field(
        min_length=1,
        description="Confirmed call identifier, e.g. HORIZON-CL5-2024-D3-02.",
    )
    topic_id: str = Field(min_length=1, description="Confirmed topic id within the call.")
    year: int = Field(ge=2014, le=2099, description="Call year (2014-2099).")
    outcome: SourceStatus = Field(
        description=(
            "Confirmed source-status of the proposal as a whole. The chunker "
            "stamps this onto every emitted chunk's ``source_status``; the "
            "metadata.py drift validator enforces equality."
        ),
    )
    proposal_title: str | None = Field(default=None, description="Optional proposal title.")
    consortium_acronym: str | None = Field(
        default=None,
        description="Optional consortium acronym, e.g. STP.",
    )
    language: str = Field(default="en", description="ISO 639-1 language code.")
    force: bool = Field(
        default=False,
        description=(
            "Override the soft-duplicate warning emitted when an existing "
            "record matches by (proposal_title, call_id) but the bytes differ. "
            "Has no effect on byte-identical (hard) duplicates."
        ),
    )


class ConfirmResponse(BaseModel):
    """What ``POST /api/ingestion/confirm`` returns once the chunks are indexed."""

    model_config = ConfigDict(extra="forbid")

    chunks_added: int = Field(ge=0, description="How many chunks landed in the index.")
    collection: str = Field(min_length=1, description="Chroma collection that received them.")
    sidecar_path: str = Field(
        min_length=1,
        description="Absolute path to the persisted YAML metadata sidecar.",
    )
    duplicate_warning: str | None = Field(
        default=None,
        description=(
            "Soft-duplicate warning surfaced when an existing record matches "
            "by (proposal_title, call_id) but the new content differs and the "
            "operator overrode the block via ``force=true``. ``None`` on the "
            "happy path."
        ),
    )
    replaced_document_id: str | None = Field(
        default=None,
        description=(
            "When non-null, the document_id whose chunks were deleted before "
            "this upsert. Set for the REINDEX (corrected-version) and forced "
            "soft-duplicate cases; ``None`` on a clean first-ingest."
        ),
    )


class EnumsResponse(BaseModel):
    """Closed enum values exposed to the UI so Selects never drift.

    The UI's programme / outcome dropdowns *must* source their options
    from this endpoint rather than hand-typing the strings. The route
    derives the lists from the Python enums directly so adding a new
    member upstream automatically appears in the form.
    """

    model_config = ConfigDict(extra="forbid")

    programme: list[str] = Field(description="Programme enum values.")
    source_status: list[str] = Field(description="SourceStatus enum values.")


# ---------------------------------------------------------------------------
# Section drafting (Task 3.1 / issue #15)
# ---------------------------------------------------------------------------


class GenerationEnumsResponse(BaseModel):
    """Closed enum vocabularies the drafting UI Selects must use.

    Mirrors :class:`EnumsResponse` for the ingestion form but exposes
    the enums the section-drafting workspace needs: which section types
    can be drafted, and which programme filters are available. Sourced
    from the Python enums directly so the UI never hand-types a string
    that could drift away from the model.
    """

    model_config = ConfigDict(extra="forbid")

    section_type: list[str] = Field(description="SectionType enum values.")
    programme: list[str] = Field(description="Programme enum values.")


class DraftingProfileSummary(BaseModel):
    """One drafting profile entry exposed to the UI Select.

    ``programme`` is the enum value (e.g. ``horizon_europe``) so the UI
    can post it back unchanged to ``POST /api/generation/section`` as
    ``profile_programme``. ``name`` is the human-readable label rendered
    in the Select option.
    """

    model_config = ConfigDict(extra="forbid")

    programme: Programme = Field(description="Programme this profile applies to.")
    name: str = Field(min_length=1, description="Human-readable profile name.")


class ProfilesResponse(BaseModel):
    """``GET /api/generation/profiles`` — list of available drafting profiles."""

    model_config = ConfigDict(extra="forbid")

    profiles: list[DraftingProfileSummary] = Field(
        default_factory=list,
        description=(
            "Drafting profiles bundled with this build. Empty list is a "
            "legal state — the workflow falls back to generic guidance "
            "when no profile is selected."
        ),
    )


class GenerateSectionRequest(BaseModel):
    """Operator-facing wire model for ``POST /api/generation/section``.

    Mirrors only the fields the React workspace lets the user edit. The
    server constructs :class:`~eurpe.generation.GenerationRequest` from
    these values inside the route handler so the public wire surface
    stays narrow and stable.

    Empty / incomplete inputs are rejected at the boundary so AC #4
    ("Empty or incomplete inputs show actionable validation messages")
    fires server-side too — the React client validates first, but a
    bypassed client must still get a clean 422.
    """

    model_config = ConfigDict(extra="forbid")

    section_type: SectionType = Field(
        description=(
            "Which section to draft. Must be one of the values "
            "advertised by ``GET /api/generation/enums``."
        ),
    )
    user_intent: str = Field(
        min_length=1,
        description=(
            "What the user wants this section to communicate. The single "
            "most important free-text field — drives retrieval and is "
            "quoted verbatim in the prompt."
        ),
    )
    call_context: str = Field(
        default="",
        description=(
            "Optional pasted call / topic text. Free-text. Passed verbatim "
            "to the generation workflow."
        ),
    )
    target_programme: Programme | None = Field(
        default=None,
        description=(
            "Optional programme filter for retrieval. ``None`` retrieves "
            "across all programmes."
        ),
    )
    profile_programme: Programme | None = Field(
        default=None,
        description=(
            "Programme whose drafting profile should be applied. The "
            "service resolves this via :func:`load_profile`. ``None`` "
            "uses the workflow's generic guidance."
        ),
    )
    top_k_examples: int = Field(
        default=5,
        ge=1,
        le=20,
        description=(
            "Number of past-proposal examples to retrieve. Mirrors the "
            "workflow's per-call top_k_examples knob."
        ),
    )
    lessons_learned: bool = Field(
        default=False,
        description=(
            "Surface rejected examples more aggressively as cautionary "
            "evidence. Mirrors the workflow's per-call lessons_learned "
            "override."
        ),
    )


class CitationPayload(BaseModel):
    """One citation rendered alongside the draft.

    Flat shape (not nested) so the React client can render a table row
    per entry without unwrapping nested objects. Field names mirror
    :class:`eurpe.generation.CitationRef` so the wire format is a
    direct serialisation of the workflow's structured output.
    """

    model_config = ConfigDict(extra="forbid")

    citation_id: int = Field(ge=1, description="1-indexed marker [N] in draft text.")
    source_status: SourceStatus = Field(description="Provenance label of the cited chunk.")
    programme: Programme = Field(description="Programme of the cited proposal's call.")
    call_id: str = Field(min_length=1, description="Call identifier.")
    proposal_title: str | None = Field(default=None, description="Title of the cited proposal.")
    section_heading: str | None = Field(default=None, description="Source section heading.")
    page: int | None = Field(default=None, ge=1, description="1-indexed source page number.")
    chunk_id: str = Field(min_length=1, description="Stable chunk identifier.")
    snippet: str = Field(description="Short excerpt of the source chunk.")


class GenerateSectionResponse(BaseModel):
    """``POST /api/generation/section`` — generated draft + citations.

    ``text`` is markdown the React client renders to the operator;
    ``citations`` is the 1-to-1 list of ``[N]`` references the LLM used.
    ``model`` and ``drafting_profile`` are returned for the audit footer
    the UI displays under the draft so the operator can verify *which*
    model and profile shaped the output without inspecting logs.
    """

    model_config = ConfigDict(extra="forbid")

    section_type: SectionType = Field(description="Section that was drafted.")
    text: str = Field(min_length=1, description="Generated draft markdown.")
    citations: list[CitationPayload] = Field(
        default_factory=list,
        description="Citations referenced by the draft. May be empty.",
    )
    model: str = Field(min_length=1, description="LLM identifier that produced the draft.")
    generated_at: datetime = Field(description="UTC timestamp when the draft was assembled.")
    drafting_profile: str | None = Field(
        default=None,
        description="Profile applied to the draft, when one was selected.",
    )
