import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

import type {
  CitationPayload,
  GenerateSectionResponse,
  IterationRecordPayload,
} from "./api";

interface Props {
  draft: GenerateSectionResponse;
}

/**
 * Visible source-status badge per :class:`SourceStatus` value.
 *
 * Mirrors the Markdown badges produced by
 * :class:`eurpe.generation.render.MarkdownCitationRenderer` so an
 * operator who learnt the badge vocabulary from a CLI-rendered draft
 * sees the same glyph here. The plain text label is rendered alongside
 * so a screen reader does not depend on the glyph for meaning.
 */
const STATUS_BADGE: Record<string, { glyph: string; label: string; tone: string }> = {
  funded: {
    glyph: "✓",
    label: "FUNDED",
    tone: "bg-green-100 text-green-800 border-green-200",
  },
  rejected: {
    glyph: "✗",
    label: "REJECTED",
    tone: "bg-red-100 text-red-800 border-red-200",
  },
  esr_note: {
    glyph: "ⓘ",
    label: "ESR ADVISORY",
    tone: "bg-blue-100 text-blue-800 border-blue-200",
  },
  unknown: {
    glyph: "?",
    label: "UNKNOWN",
    tone: "bg-slate-100 text-slate-800 border-slate-200",
  },
};

const STATUS_CAVEAT: Record<string, string> = {
  funded: "",
  rejected: "Cautionary lesson — this proposal was NOT funded.",
  esr_note: "Reviewer commentary — advisory only, not ground truth.",
  unknown: "Source status unverified — treat with caution.",
};

function humanizeSectionType(value: string): string {
  return value
    .split("_")
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1))
    .join(" ");
}

function humanizeProgramme(value: string): string {
  return humanizeSectionType(value);
}

function formatTimestamp(iso: string): string {
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

/**
 * Render a generated section draft alongside its citations.
 *
 * Layout:
 *
 * 1. Section heading + audit footer (model / profile / timestamp).
 * 2. The draft markdown text in a ``pre``-wrapped block so the
 *    inline ``[N]`` markers line up with the citation list below.
 * 3. A citation table per chunk, with the same status badges the
 *    CLI renderer uses so an operator who reviewed a CLI-generated
 *    draft sees the same vocabulary here.
 *
 * The component intentionally does not render the draft text as
 * HTML/Markdown — the v1 UI keeps the inline ``[N]`` markers visible
 * so an operator can scan them against the table. A Markdown-to-HTML
 * step belongs in a follow-up issue (Task 3.5 covers export polish).
 */
export function DraftPreview({ draft }: Props) {
  return (
    <Card data-testid="draft-preview">
      <CardHeader>
        <CardTitle className="flex items-baseline justify-between gap-3">
          <span>{humanizeSectionType(draft.section_type)}</span>
          <span className="text-xs font-normal text-muted-foreground">
            {draft.citations.length} citation{draft.citations.length === 1 ? "" : "s"}
          </span>
        </CardTitle>
        <CardDescription>
          Generated by <code>{draft.model}</code>
          {draft.drafting_profile ? (
            <>
              {" "}
              · profile <code>{draft.drafting_profile}</code>
            </>
          ) : (
            <> · no profile applied</>
          )}{" "}
          · {formatTimestamp(draft.generated_at)}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <pre className="whitespace-pre-wrap rounded-md bg-muted px-4 py-3 text-sm leading-relaxed">
          {draft.text}
        </pre>
        <Citations citations={draft.citations} />
        <IterationHistory iterations={draft.iterations} />
      </CardContent>
    </Card>
  );
}

/**
 * Render the critic-loop iteration history (Task 3.2 / issue #16).
 *
 * Each entry surfaces the three pieces of evidence that AC #3 requires:
 *
 * 1. ``iteration_index`` — which pass this is.
 * 2. ``changes_summary`` — what changed since the prior iteration
 *    (text/citation deltas + a one-line narrative).
 * 3. ``requirements_checked`` — the deterministic list of call/profile
 *    requirements the critic was instructed to evaluate.
 *
 * The full critique text is rendered in a collapsible details block so
 * the summary view stays compact. Empty list (single-pass draft)
 * renders nothing — the section header would be noise.
 */
function IterationHistory({
  iterations,
}: {
  iterations: IterationRecordPayload[];
}) {
  if (iterations.length === 0) {
    return null;
  }
  return (
    <div data-testid="iteration-history">
      <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
        Critic loop history ({iterations.length}{" "}
        iteration{iterations.length === 1 ? "" : "s"})
      </h3>
      <ol className="space-y-3">
        {iterations.map((it) => (
          <IterationEntry key={it.iteration_index} iteration={it} />
        ))}
      </ol>
    </div>
  );
}

function IterationEntry({ iteration }: { iteration: IterationRecordPayload }) {
  return (
    <li
      className="rounded-md border p-3"
      data-testid={`iteration-${iteration.iteration_index}`}
    >
      <div className="flex flex-wrap items-baseline justify-between gap-2 text-sm">
        <span className="font-medium">
          Iteration {iteration.iteration_index}
        </span>
        <span className="text-xs text-muted-foreground">
          {formatTimestamp(iteration.generated_at)}
        </span>
      </div>
      <p className="mt-1 text-sm">{iteration.changes_summary}</p>
      <div className="mt-2">
        <h4 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Requirements checked ({iteration.requirements_checked.length})
        </h4>
        <ul className="mt-1 flex flex-wrap gap-1">
          {iteration.requirements_checked.map((req) => (
            <li
              key={req}
              className="rounded-md border bg-muted px-2 py-0.5 text-xs"
            >
              {req}
            </li>
          ))}
        </ul>
      </div>
      <details className="mt-2 text-xs">
        <summary className="cursor-pointer text-muted-foreground">
          Show critique text
        </summary>
        <pre className="mt-2 whitespace-pre-wrap rounded-md bg-muted px-3 py-2 text-xs leading-relaxed">
          {iteration.critique_text}
        </pre>
      </details>
    </li>
  );
}

function Citations({ citations }: { citations: CitationPayload[] }) {
  if (citations.length === 0) {
    return (
      <div
        role="status"
        className="rounded-md border border-dashed bg-muted/40 px-4 py-3 text-sm text-muted-foreground"
      >
        No citations were attached to this draft. Re-run with a more specific intent or a
        wider retrieval window if you expected evidence to be quoted.
      </div>
    );
  }

  return (
    <div>
      <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
        Citations
      </h3>
      <ul className="space-y-3">
        {citations.map((c) => (
          <CitationCard key={`${c.citation_id}-${c.chunk_id}`} citation={c} />
        ))}
      </ul>
    </div>
  );
}

function CitationCard({ citation }: { citation: CitationPayload }) {
  const badge =
    STATUS_BADGE[citation.source_status] ?? STATUS_BADGE.unknown;
  const caveat = STATUS_CAVEAT[citation.source_status] ?? STATUS_CAVEAT.unknown;
  const page = citation.page !== null ? `p. ${citation.page}` : "p. n/a";
  const section = citation.section_heading ? `§${citation.section_heading}` : "§n/a";
  return (
    <li className="rounded-md border p-3" data-testid="citation-card">
      <div className="flex flex-wrap items-center gap-2 text-sm">
        <span className="rounded-md bg-muted px-2 py-0.5 font-mono text-xs">
          [{citation.citation_id}]
        </span>
        <span
          className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-xs font-medium ${badge.tone}`}
        >
          <span aria-hidden="true">{badge.glyph}</span>
          <span>{badge.label}</span>
        </span>
        <span className="text-xs text-muted-foreground">
          {humanizeProgramme(citation.programme)} call{" "}
          <code className="rounded bg-muted px-1 py-0.5">{citation.call_id}</code>, {page}, {section}
        </span>
      </div>
      {citation.proposal_title && (
        <p className="mt-1 text-xs text-muted-foreground">
          Source: <em>{citation.proposal_title}</em>
        </p>
      )}
      <blockquote className="mt-2 border-l-2 pl-3 text-xs italic text-muted-foreground">
        “{citation.snippet}”
      </blockquote>
      {caveat && (
        <p className="mt-2 text-xs italic text-muted-foreground">{caveat}</p>
      )}
    </li>
  );
}
